### ISSUE TITLE
Scoreboard.result attribute not working with cocotb 2.0.0b1

### ISSUE THREAD

**Issue by jontindal** [cocotb/cocotb-bus#96]
Scoreboard.result attribute will return `TestSuccess()` (deprecated in 2.0.0b1), which now has a required msg argument.
This means any attempt to access the result attribute results in the following error:
```
Traceback (most recent call last):
  File "<cwd>/.venv/lib/python3.10/site-packages/cocotb/_test_factory.py", line 282, in _my_test
    await self.test_function(dut, *self.args, **kwargs)
  File "<cwd>/tests/test_ahb_lite_monitor_scoreboard.py", line 173, in run_test
    raise scoreboard.result
  File "<cwd>/.venv//lib/python3.10/site-packages/cocotb_bus/scoreboard.py", line 74, in result
    return TestSuccess()
TypeError: TestSuccess.__init__() missing 1 required positional argument: 'msg'
```

In cocotb 1.9.2, `TestSuccess` used the Exception default constructor with no required arguments.
