### PR TITLE
Updates for cocotb2.0

### LINKED ISSUE #96: Scoreboard.result attribute not working with cocotb 2.0.0b1
Scoreboard.result attribute will return `TestSuccess()` (deprecated in 2.0.0b1), which now has a required msg argument.
This means any attempt to access the result attribute results in the following error:
```
Traceback (most recent call last):
  File "<cwd>/.venv/lib/python3.10/site-packages/cocotb/_test_factory.py", line 282, in _my_test
    await self.test_function(dut, *self.args, **kwargs)
  File "<cwd>/tests/test_ahb_lite_monitor_scoreboard.py", line 173, in run_test
    raise scoreboard.result
  File "<cwd>/.venv//lib/python3.10/site-packages/cocotb_bus/scoreboard.py", line 74, in result
    return TestSuccess()
TypeError: TestSuccess.__init__() missing 1 required positional argument: 'msg'
```

In cocotb 1.9.2, `TestSuccess` used the Exception default constructor with no required arguments.

### PR DESCRIPTION
**Pull request by RiceShelley**
* Fixed python 3.6 issue with CI
* Added cocotb2.0 to CI testing
* Made code changes to make CI pass. Most changes are a results of following the cocotb2.0 [upgrade guide](https://docs.cocotb.org/en/development/upgrade-2.0.html).

Fixes #96

### CODE REVIEW

**Comment by RiceShelley** [comment]
Thanks for the review @cmarqu is anything keeping this from merging? Also does cocotb-bus have a release planned?

File: src/cocotb_bus/scoreboard.py [hunk 1]
```diff
@@ -71,7 +71,7 @@ def result(self):
                 fail = True
         assert not fail, "Not all expected output was received"
         assert not self.errors, "Errors were recorded during the test"
-        return TestSuccess()
+        return test_success()
```
Comment (ktbarrett) [inline src/cocotb_bus/scoreboard.py:74]: `cocotb.pass_test` does not return a `TestSuccess`, but immediately ends the test.
```suggestion
        test_success()
```
This is an interface breaking change and we will need to bump the version of cocotb-bus, but that's okay and expected. I seriously doubt anyone is using `Scoreboard`. It's a goddamn mess.

**Comment by ktbarrett** [comment]
I don't think we will cut a release immediately. There's a lot of stuff in the `compat` library that's unnecessary that I have refactored out chilling on a branch rn. Let's get this in though.

File: src/cocotb_bus/scoreboard.py (hunk 1 above)
Comment (RiceShelley) [reply src/cocotb_bus/scoreboard.py]: Apologies for not getting around to making the final changes quick enough. I'm curious what you would recommend for a Scoreboard? I have been using cocotb-bus Scoreboard so If there is something better I'd be happy to use it.

Comment (ktbarrett) [reply src/cocotb_bus/scoreboard.py]: I actually kept the code you wrote instead of what's here.

I'm surprised it works for you. It had some very weird behavior were couldn't reconcile when str or bytes were put into it. Maybe it's fine for other types.
